apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: ClusterIP # Servicio Privado
  selector:
    app: database
  ports:
  - port: 1521
    targetPort: 1521
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: gvenzl/oracle-xe:21.3.0
        env:
        - name: ORACLE_PASSWORD
          value: mypass
        - name: APP_USER
          value: appuser
        - name: APP_USER_PASSWORD
          value: myapppass
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 1521
